# Generated by Django 5.0.6 on 2024-06-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_shop', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_img',
            new_name='image',
        ),
    ]
